name: presence_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.4.0
  firebase_auth: 4.2.1
  cloud_firestore: 4.2.0
  firebase_storage: 11.0.8
  flutter: 
    sdk: flutter
  dropdown_button2: ^1.9.2
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  convex_bottom_bar: ^3.1.0+1
  intl: ^0.17.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  syncfusion_flutter_datepicker: ^20.4.42
  fluttertoast: ^8.1.2
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.9.2 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/icon/ic_galaxyBridges.png"

flutter: 
  uses-material-design: true

